import tkinter as tk
from tkinter import ttk
from quiz_brain import QuizBrain


THEME_COLOR = "#9E9BF2"
PINK = "#F2C4E2"
RED = "#F22D1B"
GREEN = "#3FB2BF"
YELLOW = "#F2CA50"
OFF_WHITE = "#F2E8DF"
BROWN = "#593C4C"


class Application(tk.Tk):

    def __init__(self, quiz: QuizBrain):
        self.quizzler = quiz
        super().__init__()
        self.title("qRizzler")
        self.geometry("500x625+500+50")
        self.configure(bg=OFF_WHITE, cursor="heart")

        self.main_frame = tk.Frame(bg=OFF_WHITE,padx=50, pady=30)
        self.main_frame.pack()
        
        self.score_label = tk.Label(master=self.main_frame, text="SCORE: 0", font=("Brass Mono", 17, "italic"), foreground=BROWN, background=OFF_WHITE)
        self.score_label.grid(column=1, row=0, sticky="NE")

        self.canvas = tk.Canvas(master=self.main_frame, width=400, height=400, bg=THEME_COLOR, highlightbackground=BROWN)
        self.txt = self.canvas.create_text(200, 200, font=("Brass Mono", 20, "bold"), fill=BROWN, width=380, text="Lorem Ipsum\nThis text was definitely\ngenerated by a computer.")
        self.canvas.grid(column=0, row=1, columnspan=2)

        self.true_butt = tk.Button(master=self.main_frame, bg=PINK, fg=BROWN, text="TRUE", highlightthickness=0 ,font=("Dogica", 17), width=6, pady=20, padx=20, cursor="plus", command=self.shayad_sahi)
        self.true_butt.grid(column=0, row=2, pady=30)

        self.false_butt = tk.Button(master=self.main_frame, bg=PINK, fg=BROWN, text="FALSE", highlightthickness=0 ,font=("Dogica", 17), pady=20, padx=20, cursor="plus", command=self.shayad_galat)
        self.false_butt.grid(column=1, row=2, pady=30)

        self.update_question()


    def update_question(self):
        self.canvas.config(bg=THEME_COLOR)
        self.score_label.config(text=f"SCORE: {self.quizzler.score}")
        if self.quizzler.still_has_questions():
            q_text =  self.quizzler.next_question()
            self.canvas.itemconfig(self.txt, text=q_text)
        else:
            self.canvas.itemconfig(self.txt, text="You've Reached The End Of The Quiz!")
            self.true_butt.config(state="disabled")
            self.false_butt.config(state="disabled")


    def shayad_sahi(self):
        self.show_feedback(self.quizzler.check_answer(user_answer="True"))

    def shayad_galat(self):
        self.show_feedback(self.quizzler.check_answer(user_answer="False"))

    def show_feedback(self, is_right):
        if is_right:
            self.canvas.config(bg=GREEN)
            self.after(1000, self.update_question)
        else:
            self.canvas.config(bg=RED)
            self.after(1000, self.update_question)




"""if __name__ == "__main__":
    app = Application(quiz_rn)
    app.mainloop()        """